name: Deploy Web App to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'smart-career-frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: smart-career-frontend

      - name: Build
        run: |
          npm run build
          cp dist/index.html dist/404.html
        working-directory: smart-career-frontend

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: smart-career-frontend/dist
          branch: gh-pages

